version: '3.8'
services:
  nextjs:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    command: yarn dev
    depends_on:
      - strapi

  strapi:
    build: 
      context: ./backend
    ports:
      - 1337:1337
    volumes:
      - ./backend:/srv/app
    command: yarn develop
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: inilah-blog
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
